version: 2.1
orbs:
  ft-golang-ci: financial-times/golang-ci@1
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/publish-carousel
    docker:
      - image: golang:1
        environment:
          GOPATH: /go
          MONGO_TEST_URL: localhost:27017
          ETCD_TEST_URL: http://localhost:2379
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_COVERAGE_REPORT: /tmp/coverage-results
      - image: mongo:3.2.18
      - image: quay.io/coreos/etcd:v3.2.11
    steps:
      - checkout
      - ft-golang-ci/build
      - ft-golang-ci/lint
      - ft-golang-ci/test

workflows:
  test-and-build-docker:
    jobs:
      - build
      - ft-golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build
  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          name: scan-dependencies
          context: cm-team-snyk
