# Default values for publish-carousel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/publish-carousel
  pullPolicy: Always
env: 
  mongodb: 
    url: mongodb-0.mongodb:27017
    timeout: "30000" 
  cmsnotifier: 
    url: http://cms-notifier:8080
  pam: 
    url: http://publish-availability-monitor:8080
  lagcheck: 
    url: http://kafka-lagcheck:8080
  s3: 
    bucket: com.ft.universalpublishing.publish-carousel.k8s-eu
  toggle: "true"
  throttle: "1m" 
resources:
  limits:
    memory: 256Mi


