# Default values for publish-carousel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 1
image:
  repository: coco/publish-carousel
  pullPolicy: Always
env:
  etcd_peers: NOT_AVAILABLE
  mongodb: 
    url: mongodb-new-mongodb-replicaset-0.mongodb-new-mongodb-replicaset.default.svc.cluster.local:27017, mongodb-new-mongodb-replicaset-1.mongodb-new-mongodb-replicaset.default.svc.cluster.local:27017, mongodb-new-mongodb-replicaset-2.mongodb-new-mongodb-replicaset.default.svc.cluster.local:27017
    # timeout in milliseconds
    timeout: "5000"
    node_count: 3
  cmsnotifier: 
    url: http://cms-notifier:8080
  pam: 
    url: http://publish-availability-monitor:8080
  # publishing cluster lagcheck
  lagcheck: 
    url: http://kafka-lagcheck:8080
  s3: 
    bucket: com.ft.universalpublishing.publish-carousel.k8s-eu
  toggle: "true"
  throttle: "6s"
resources:
  limits:
    memory: 256Mi


